interface MyObject {
  name: string;
  stations: string[];
}
export const subwayLines: MyObject[] = [
  {
    name: "M1a",
    stations: [
      "Atatürk Havalimanı",
      "DTM-İstanbul Fuar Merkezi",
      "Yenibosna",
      "Ataköy-Şirinevler",
      "Bahçelievler",
      "Bakırköy-İncirli",
      "Zeytinburnu",
      "Merter",
      "Davutpaşa-YTÜ",
      "Terazidere",
      "Otogar",
      "Kocatepe",
      "Sağmalcılar",
      "Bayrampaşa-Maltepe",
      "Topkapı-Ulubatlı",
      "Emniyet-Fatih",
      "Aksaray",
      "Yenikapı",
    ],
  },
  {
    name: "M1b",
    stations: [
      "Kirazlı-Bağcılar",
      "Bağcılar Meydan",
      "Üçyüzlü",
      "Menderes",
      "Esenler",
      "Otogar",
      "Kocatepe",
      "Sağmalcılar",
      "Bayrampaşa-Maltepe",
      "Topkapı-Ulubatlı",
      "Emniyet-Fatih",
      "Aksaray",
      "Yenikapı",
    ],
  },
  {
    name: "M2",
    stations: [
      "Yenikapı",
      "Vezneciler",
      "Haliç",
      "Şişhane",
      "Taksim",
      "Osmanbey",
      "Şişli-Mecidiyeköy",
      "Gayrettepe",
      "Levent",
      "4.Levent",
      "Sanayi Mahallesi",
      "Seyrantepe",
      "İTÜ Ayazağa",
      "Atatürk Oto Sanayi",
      "Darüşşafaka",
      "Hacıosman",
    ],
  },
  {
    name: "M3",
    stations: [
      "Başakşehir-Metrokent",
      "Başak Konutları",
      "Siteler",
      "Turgut Özal",
      "İkitelli Sanayi",
      "İSTOÇ",
      "Mahmutbey",
      "Yenimahalle",
      "Kirazlı-Bağcılar",
      "Onurkent",
      "Şehir Hastanesi",
      "Toplu Konutlar",
      "Kayaşehir Merkez",
    ],
  },
  {
    name: "M4",
    stations: [
      "Kadıköy",
      "Ayrılık Çeşmesi",
      "Acıbadem",
      "Ünalan",
      "Göztepe",
      "Yenisahra",
      "Kozyatağı",
      "Bostancı",
      "Küçükyalı",
      "Maltepe",
      "Huzurevi",
      "Gülsuyu",
      "Esenkent",
      "Hastane-Adliye",
      "Soğanlık",
      "Kartal",
      "Yakacık-Adnan Kahveci",
      "Pendik",
      "Tavşantepe",
      "Fevzi Çakmak-Hastane",
      "Yayalar-Şeyhli",
      "Kurtköy",
      "Sabiha Gökçen Havalimanı",
    ],
  },
  {
    name: "M5",
    stations: [
      "Üsküdar",
      "Fıstıkağacı",
      "Bağlarbaşı",
      "Altunizade",
      "Kısıklı",
      "Bulgurlu",
      "Ümraniye",
      "Çarşı",
      "Yamanevler",
      "Çakmak",
      "Ihlamurkuyu",
      "Altınşehir",
      "İmam Hatip Lisesi",
      "Dudullu",
      "Necip Fazıl",
      "Çekmeköy",
    ],
  },
  {
    name: "M6",
    stations: [
      "Levent",
      "Nispetiye",
      "Etiler",
      "Boğaziçi Üniversitesi",
      "Hisarüstü-Aşiyan",
    ],
  },
  {
    name: "M7",
    stations: [
      "Yıldız",
      "Fulya",
      "Mecidiyeköy",
      "Çağlayan",
      "Kağıthane",
      "Nurtepe",
      "Alibeyköy",
      "Çırçır",
      "Veysel Karani-Akşemsettin",
      "Yeşilpınar",
      "Kazım Karabekir",
      "Yenimahalle",
      "Karadeniz Mahallesi",
      "Tekstilkent-Giyimkent",
      "Oruç Reis",
      "Göztepe Mahallesi",
      "Mahmutbey",
    ],
  },
  {
    name: "M8",
    stations: [
      "Bostancı",
      "Emin Ali Paşa",
      "Ayşekadın",
      "Kozyatağı",
      "Küçükbakkalköy",
      "İçerenköy",
      "Kayışdağı",
      "Mevlana",
      "İmes",
      "Modoko-Keyap",
      "Dudullu",
      "Huzur",
      "Parseller",
    ],
  },
  {
    name: "M9",
    stations: ["İkitelli Sanayi", "Masko", "Bahariye"],
  },
  {
    name: "Marmaray",
    stations: [
      "Halkalı",
      "Mustafa Kemal",
      "Küçükçekmece",
      "Florya",
      "Florya Akvaryum",
      "Yeşilköy",
      "Yeşilyurt",
      "Ataköy",
      "Bakırköy",
      "Yenimahalle",
      "Zeytinburnu",
      "Kazlıçeşme",
      "Yenikapı",
      "Sirkeci",
      "Üsküdar",
      "Ayrılık Çeşmesi",
      "Söğütlüçeşme",
      "Feneryolu",
      "Göztepe",
      "Erenköy",
      "Suadiye",
      "Bostancı",
      "Küçükyalı",
      "İdealtepe",
      "Süreyya Plajı",
      "Maltepe",
      "Cevizli",
      "Atalar",
      "Başak",
      "Kartal",
      "Yunus",
      "Pendik",
      "Kaynarca",
      "Tersane",
      "Güzelyalı",
      "Aydıntepe",
      "İçmeler",
      "Tuzla",
      "Çayırova",
      "Fatih",
      "Osmangazi",
      "Darıca",
      "Gebze",
    ],
  },
];
