interface MyObject {
  name: string;
  stations: string[];
  title: string;
}
export const subwayLines: MyObject[] = [
  {
    name: "M1a",
    title: "Yenikapı - Atatürk Havalimanı",
    stations: [
      "Atatürk Havalimanı",
      "DTM-İstanbul Fuar Merkezi",
      "Yenibosna",
      "Ataköy-Şirinevler",
      "Bahçelievler",
      "Bakırköy-İncirli",
      "Zeytinburnu",
      "Merter",
      "Davutpaşa-YTÜ",
      "Terazidere",
      "Otogar",
      "Kocatepe",
      "Sağmalcılar",
      "Bayrampaşa-Maltepe",
      "Topkapı-Ulubatlı",
      "Emniyet-Fatih",
      "Aksaray",
      "Yenikapı",
    ],
  },
  {
    name: "M1b",
    title: "Yenikapı - Kirazlı",
    stations: [
      "Kirazlı-Bağcılar",
      "Bağcılar Meydan",
      "Üçyüzlü",
      "Menderes",
      "Esenler",
      "Otogar",
      "Kocatepe",
      "Sağmalcılar",
      "Bayrampaşa-Maltepe",
      "Topkapı-Ulubatlı",
      "Emniyet-Fatih",
      "Aksaray",
      "Yenikapı",
    ],
  },
  {
    name: "M2",
    title: "Yenikapı - Hacıosman",
    stations: [
      "Yenikapı",
      "Vezneciler",
      "Haliç",
      "Şişhane",
      "Taksim",
      "Osmanbey",
      "Şişli-Mecidiyeköy",
      "Gayrettepe",
      "Levent",
      "4.Levent",
      "Sanayi Mahallesi",
      "Seyrantepe",
      "İTÜ Ayazağa",
      "Atatürk Oto Sanayi",
      "Darüşşafaka",
      "Hacıosman",
    ],
  },
  {
    name: "M3",
    title: "Bakırköy - Kayaşehir",
    stations: [
      "Bakırköy Sahil",
      "Özgürlük Meydanı",
      "İncirli",
      "Haznedar",
      "İlkyuva",
      "Molla Gürani",
      "Kirazlı-Bağcılar",
      "Yenimahalle",
      "Mahmutbey",
      "İSTOÇ",
      "İkitelli Sanayi",
      "Turgut Özal",
      "Siteler",
      "Başak Konutları",
      "Başakşehir-Metrokent",
      "Onurkent",
      "Şehir Hastanesi",
      "Toplu Konutlar",
      "Kayaşehir Merkez",
    ],
  },
  {
    name: "M4",
    title: "Kadıköy - Sabiha Gökçen Havalimanı",
    stations: [
      "Kadıköy",
      "Ayrılık Çeşmesi",
      "Acıbadem",
      "Ünalan",
      "Göztepe",
      "Yenisahra",
      "Kozyatağı",
      "Bostancı",
      "Küçükyalı",
      "Maltepe",
      "Huzurevi",
      "Gülsuyu",
      "Esenkent",
      "Hastane-Adliye",
      "Soğanlık",
      "Kartal",
      "Yakacık-Adnan Kahveci",
      "Pendik",
      "Tavşantepe",
      "Fevzi Çakmak-Hastane",
      "Yayalar-Şeyhli",
      "Kurtköy",
      "Sabiha Gökçen Havalimanı",
    ],
  },
  {
    name: "M5",
    title: "Üsküdar - Samandıra",
    stations: [
      "Üsküdar",
      "Fıstıkağacı",
      "Bağlarbaşı",
      "Altunizade",
      "Kısıklı",
      "Bulgurlu",
      "Ümraniye",
      "Çarşı",
      "Yamanevler",
      "Çakmak",
      "Ihlamurkuyu",
      "Altınşehir",
      "İmam Hatip Lisesi",
      "Dudullu",
      "Necip Fazıl",
      "Çekmeköy",
      "Meclis",
      "Sarıgazi",
      "Sancaktepe",
      "Samandıra Merkez",
    ],
  },
  {
    name: "M6",
    title: "Levent - Hisarüstü",
    stations: [
      "Levent",
      "Nispetiye",
      "Etiler",
      "Boğaziçi Üniversitesi",
      "Hisarüstü-Aşiyan",
    ],
  },
  {
    name: "M7",
    title: "Yıldız - Mahmutbey",
    stations: [
      "Yıldız",
      "Fulya",
      "Mecidiyeköy",
      "Çağlayan",
      "Kağıthane",
      "Nurtepe",
      "Alibeyköy",
      "Çırçır",
      "Veysel Karani-Akşemsettin",
      "Yeşilpınar",
      "Kazım Karabekir",
      "Yenimahalle",
      "Karadeniz Mahallesi",
      "Tekstilkent-Giyimkent",
      "Oruç Reis",
      "Göztepe Mahallesi",
      "Mahmutbey",
    ],
  },
  {
    name: "M8",
    title: "Bostancı - Parseller",
    stations: [
      "Bostancı",
      "Emin Ali Paşa",
      "Ayşekadın",
      "Kozyatağı",
      "Küçükbakkalköy",
      "İçerenköy",
      "Kayışdağı",
      "Mevlana",
      "İmes",
      "Modoko-Keyap",
      "Dudullu",
      "Huzur",
      "Parseller",
    ],
  },
  {
    name: "M9",
    title: "Ataköy - Olimpiyat",
    stations: [
      "Olimpiyat",
      "Ziya Gökalp Mahallesi",
      "İkitelli Sanayi",
      "Masko",
      "Bahariye",
      "Atatürk Mahallesi",
      "Halkalı Caddesi",
      "15 Temmuz",
      "Doğu Sanayi",
      "29 Ekim - Cumhuriyet",
      "Çobançeşme",
      "Yenibosna",
      "Ataköy",
    ],
  },
  {
    name: "M11",
    title: "Gayrettepe - İstanbul Airport",
    stations: [
      "Gayrettepe",
      "Kağıthane",
      "Hasdal",
      "Kemerburgaz",
      "Göktürk",
      "İhsaniye",
      "İstanbul Havalimanı",
      "Kargo Terminal",
      "Taşoluk",
      "Arnavutköy Hastane",
    ],
  },
  {
    name: "Marmaray",
    title: "Halkalı - Gebze",
    stations: [
      "Halkalı",
      "Mustafa Kemal",
      "Küçükçekmece",
      "Florya",
      "Florya Akvaryum",
      "Yeşilköy",
      "Yeşilyurt",
      "Ataköy",
      "Bakırköy",
      "Yenimahalle",
      "Zeytinburnu",
      "Kazlıçeşme",
      "Yenikapı",
      "Sirkeci",
      "Üsküdar",
      "Ayrılık Çeşmesi",
      "Söğütlüçeşme",
      "Feneryolu",
      "Göztepe",
      "Erenköy",
      "Suadiye",
      "Bostancı",
      "Küçükyalı",
      "İdealtepe",
      "Süreyya Plajı",
      "Maltepe",
      "Cevizli",
      "Atalar",
      "Başak",
      "Kartal",
      "Yunus",
      "Pendik",
      "Kaynarca",
      "Tersane",
      "Güzelyalı",
      "Aydıntepe",
      "İçmeler",
      "Tuzla",
      "Çayırova",
      "Fatih",
      "Osmangazi",
      "Darıca",
      "Gebze",
    ],
  },

  {
    name: "T1",
    title: "Kabataş - Bağcılar",
    stations: [
      "Bağcılar",
      "Güneştepe",
      "Yavuzselim",
      "Soğanlı",
      "Akıncılar",
      "Güngören",
      "Merter Tekstil Merkezi",
      "Mehmet Akif",
      "Zeytinburnu",
      "Mithatpaşa",
      "Seyitnizam-Akşemsettin",
      "Merkezefendi",
      "Cevizlibağ-AÖY",
      "Topkapı",
      "Pazartekke",
      "Çapa-Şehremini",
      "Fındıkzade",
      "Haseki",
      "Yusufpaşa",
      "Aksaray",
      "Laleli-İstanbul Ü.",
      "Beyazı-Kapalıçarşı",
      "Çemberlitaş",
      "Sultanahmet",
      "Gülhane",
      "Sirkeci",
      "Eminönü",
      "Karaköy",
      "Tophane",
      "Fındıklı-Mimar Sinan Ü.",
      "Kabataş",
    ],
  },
  {
    name: "T3",
    title: "Kadıköy - Moda",
    stations: [
      "İskele Cami",
      "Çarşı",
      "Altıyol",
      "Bahariye",
      "Kilise",
      "Moda İlkokulu",
      "Moda Caddesi",
      "Rızapaşa",
      "Mühürdar",
      "Damga Sokak",
      "Kadıköy İDO",
    ],
  },
  {
    name: "T4",
    title: "Topkapı - Mescid-i Selam",
    stations: [
      "Mescid-i Selam",
      "Cebeci",
      "Sultançiftliği",
      "Yenimahalle",
      "Hacı Şükrü",
      "50.Yıl-Baştabya",
      "Cumhuriyet Mahallesi",
      "Kiptaş-Venezia",
      "Karadeniz",
      "Taşköprü",
      "Ali Fuat Başgil",
      "Bosna Çukurçeşme",
      "Sağmalcılar",
      "Uluyol Bereç",
      "Rami",
      "Topçular",
      "Demirkapı",
      "Şehitlik",
      "Edirnekapı",
      "Vatan",
      "Fetihkapı",
      "Topkapı",
    ],
  },
  {
    name: "T5",
    title: "Eminönü - Alibeyköy",
    stations: [
      "Eminönü",
      "Küçükpazar",
      "Cibali",
      "Fener",
      "Balat",
      "Ayvansaray",
      "Feshane",
      "Eyüpsultan Teleferik",
      "Eyüpsultan Devlet Hastanesi",
      "Silahtarağa Mahallesi",
      "Üniversite",
      "Alibeyköy Merkez",
      "Alibeyköy Metro",
      "Alibeyköy Cep Otogarı",
    ],
  },
  {
    name: "F1",
    title: "Kabataş - Taksim",
    stations: ["Kabataş", "Taksim"],
  },
  {
    name: "F4",
    title: "Hisarüstü - Aşiyan",
    stations: ["Kabataş", "Taksim"],
  },
];
